// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIssueAlert(args: GetIssueAlertArgs, opts?: pulumi.InvokeOptions): Promise<GetIssueAlertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sentry:index/getIssueAlert:getIssueAlert", {
        "id": args.id,
        "organization": args.organization,
        "project": args.project,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIssueAlert.
 */
export interface GetIssueAlertArgs {
    id: string;
    organization: string;
    project: string;
}

/**
 * A collection of values returned by getIssueAlert.
 */
export interface GetIssueAlertResult {
    readonly actionMatch: string;
    readonly actions: string;
    readonly actionsV2s: outputs.GetIssueAlertActionsV2[];
    readonly conditions: string;
    readonly conditionsV2s: outputs.GetIssueAlertConditionsV2[];
    readonly environment: string;
    readonly filterMatch: string;
    readonly filters: string;
    readonly filtersV2s: outputs.GetIssueAlertFiltersV2[];
    readonly frequency: number;
    readonly id: string;
    readonly name: string;
    readonly organization: string;
    readonly owner: string;
    readonly project: string;
}
export function getIssueAlertOutput(args: GetIssueAlertOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIssueAlertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sentry:index/getIssueAlert:getIssueAlert", {
        "id": args.id,
        "organization": args.organization,
        "project": args.project,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIssueAlert.
 */
export interface GetIssueAlertOutputArgs {
    id: pulumi.Input<string>;
    organization: pulumi.Input<string>;
    project: pulumi.Input<string>;
}
