// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getKey(args: GetKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sentry:index/getKey:getKey", {
        "first": args.first,
        "id": args.id,
        "name": args.name,
        "organization": args.organization,
        "project": args.project,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKey.
 */
export interface GetKeyArgs {
    first?: boolean;
    id?: string;
    name?: string;
    organization: string;
    project: string;
}

/**
 * A collection of values returned by getKey.
 */
export interface GetKeyResult {
    readonly dsn: {[key: string]: string};
    /**
     * @deprecated Deprecated
     */
    readonly dsnCsp: string;
    /**
     * @deprecated Deprecated
     */
    readonly dsnPublic: string;
    /**
     * @deprecated Deprecated
     */
    readonly dsnSecret: string;
    readonly first?: boolean;
    readonly id?: string;
    readonly javascriptLoaderScript: outputs.GetKeyJavascriptLoaderScript;
    readonly name?: string;
    readonly organization: string;
    readonly project: string;
    readonly projectId: string;
    readonly public: string;
    readonly rateLimitCount: number;
    readonly rateLimitWindow: number;
    readonly secret: string;
}
export function getKeyOutput(args: GetKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sentry:index/getKey:getKey", {
        "first": args.first,
        "id": args.id,
        "name": args.name,
        "organization": args.organization,
        "project": args.project,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKey.
 */
export interface GetKeyOutputArgs {
    first?: pulumi.Input<boolean>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    organization: pulumi.Input<string>;
    project: pulumi.Input<string>;
}
